# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 01:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyname', models.CharField(max_length=200)),
                ('logo', models.FileField(upload_to=b'')),
                ('ratings', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Jobpost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobTitle', models.CharField(max_length=200)),
                ('jobCity', models.CharField(max_length=200)),
                ('jobType', models.CharField(max_length=200)),
                ('pubDate', models.DateField(verbose_name=b'date published')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.Company')),
            ],
        ),
    ]
