# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 00:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20160629_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='jobType',
            field=models.CharField(choices=[(b'FR', b'Full time'), (b'SO', b'Part Time'), (b'JR', b'Contract'), (b'SR', b'Freelance')], max_length=200),
        ),
    ]
