# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 00:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20160701_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='jobType',
            field=models.CharField(choices=[(b'FT', b'Full time'), (b'PT', b'Part Time'), (b'CT', b'Contract'), (b'FL', b'Freelance')], max_length=200),
        ),
    ]
