# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 00:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20160701_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='jobDetails',
            field=models.TextField(default=b'', max_length=10000),
        ),
    ]
