# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 01:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_jobpost_jobdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='jobType',
            field=models.CharField(choices=[(b'Full Time', b'fulltime'), (b'Part Time', b'parttime'), (b'Contract', b'contract'), (b'Free Lance', b'freelance')], max_length=200),
        ),
    ]
