# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 01:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_auto_20160701_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='jobType',
            field=models.CharField(choices=[(b'FullTime', b'full time'), (b'PartTime', b'part time'), (b'Contract', b'contract'), (b'Free Lance', b'freelance')], max_length=200),
        ),
    ]
